// Date: 7/12/2014 3:21:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package joazlazer.mods.amc.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAwakeningTable extends ModelBase
{
    //fields
    ModelRenderer Base;
    ModelRenderer Corner1;
    ModelRenderer Corner2;
    ModelRenderer Corner3;
    ModelRenderer Corner4;
    ModelRenderer Bookshelve;
    ModelRenderer Base2;
    ModelRenderer TCorner1;
    ModelRenderer TCorner2;
    ModelRenderer TCorner3;
    ModelRenderer TCorner4;
    ModelRenderer Top;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;

    public ModelAwakeningTable()
    {
        textureWidth = 128;
        textureHeight = 128;

        Base = new ModelRenderer(this, 64, 35);
        Base.addBox(0F, 0F, 0F, 16, 1, 16);
        Base.setRotationPoint(-8F, 23F, -8F);
        Base.setTextureSize(128, 128);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Corner1 = new ModelRenderer(this, 0, 32);
        Corner1.addBox(0F, 0F, 0F, 1, 6, 1);
        Corner1.setRotationPoint(-8F, 17F, -8F);
        Corner1.setTextureSize(128, 128);
        Corner1.mirror = true;
        setRotation(Corner1, 0F, 0F, 0F);
        Corner2 = new ModelRenderer(this, 0, 32);
        Corner2.addBox(0F, 0F, 0F, 1, 6, 1);
        Corner2.setRotationPoint(7F, 17F, -8F);
        Corner2.setTextureSize(128, 128);
        Corner2.mirror = true;
        setRotation(Corner2, 0F, 0F, 0F);
        Corner3 = new ModelRenderer(this, 0, 32);
        Corner3.addBox(0F, 0F, 0F, 1, 6, 1);
        Corner3.setRotationPoint(7F, 17F, 7F);
        Corner3.setTextureSize(128, 128);
        Corner3.mirror = true;
        setRotation(Corner3, 0F, 0F, 0F);
        Corner4 = new ModelRenderer(this, 0, 32);
        Corner4.addBox(0F, 0F, 0F, 1, 6, 1);
        Corner4.setRotationPoint(-8F, 17F, 7F);
        Corner4.setTextureSize(128, 128);
        Corner4.mirror = true;
        setRotation(Corner4, 0F, 0F, 0F);
        Bookshelve = new ModelRenderer(this, 0, 0);
        Bookshelve.addBox(0F, 0F, 0F, 14, 6, 14);
        Bookshelve.setRotationPoint(-7F, 17F, -7F);
        Bookshelve.setTextureSize(128, 128);
        Bookshelve.mirror = true;
        setRotation(Bookshelve, 0F, 0F, 0F);
        Base2 = new ModelRenderer(this, 64, 0);
        Base2.addBox(0F, 0F, 0F, 16, 1, 16);
        Base2.setRotationPoint(-8F, 16F, -8F);
        Base2.setTextureSize(128, 128);
        Base2.mirror = true;
        setRotation(Base2, 0F, 0F, 0F);
        TCorner1 = new ModelRenderer(this, 0, 42);
        TCorner1.addBox(0F, 0F, 0F, 3, 6, 3);
        TCorner1.setRotationPoint(5F, 10F, -8F);
        TCorner1.setTextureSize(128, 128);
        TCorner1.mirror = true;
        setRotation(TCorner1, 0F, 0F, 0F);
        TCorner2 = new ModelRenderer(this, 0, 51);
        TCorner2.addBox(0F, 0F, 0F, 3, 6, 3);
        TCorner2.setRotationPoint(-8F, 10F, 5F);
        TCorner2.setTextureSize(128, 128);
        TCorner2.mirror = true;
        setRotation(TCorner2, 0F, 0F, 0F);
        TCorner3 = new ModelRenderer(this, 0, 60);
        TCorner3.addBox(0F, 0F, 0F, 3, 6, 3);
        TCorner3.setRotationPoint(5F, 10F, 5F);
        TCorner3.setTextureSize(128, 128);
        TCorner3.mirror = true;
        setRotation(TCorner3, 0F, 0F, 0F);
        TCorner4 = new ModelRenderer(this, 0, 23);
        TCorner4.addBox(0F, 0F, 0F, 3, 6, 3);
        TCorner4.setRotationPoint(-8F, 10F, -8F);
        TCorner4.setTextureSize(128, 128);
        TCorner4.mirror = true;
        setRotation(TCorner4, 0F, 0F, 0F);
        Top = new ModelRenderer(this, 64, 17);
        Top.addBox(0F, 0F, 0F, 16, 2, 16);
        Top.setRotationPoint(-8F, 8F, -8F);
        Top.setTextureSize(128, 128);
        Top.mirror = true;
        setRotation(Top, 0F, 0F, 0F);
        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(0F, 0F, 0F, 1, 1, 3);
        Shape1.setRotationPoint(4F, 10F, 5F);
        Shape1.setTextureSize(128, 128);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new ModelRenderer(this, 0, 0);
        Shape2.addBox(0F, 0F, 0F, 3, 1, 1);
        Shape2.setRotationPoint(5F, 10F, -5F);
        Shape2.setTextureSize(128, 128);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new ModelRenderer(this, 0, 0);
        Shape3.addBox(0F, 0F, 0F, 3, 1, 1);
        Shape3.setRotationPoint(5F, 10F, 4F);
        Shape3.setTextureSize(128, 128);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new ModelRenderer(this, 0, 0);
        Shape4.addBox(0F, 0F, 0F, 1, 1, 3);
        Shape4.setRotationPoint(4F, 10F, -8F);
        Shape4.setTextureSize(128, 128);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
        Shape5 = new ModelRenderer(this, 0, 0);
        Shape5.addBox(0F, 0F, 0F, 1, 1, 3);
        Shape5.setRotationPoint(-5F, 10F, -8F);
        Shape5.setTextureSize(128, 128);
        Shape5.mirror = true;
        setRotation(Shape5, 0F, 0F, 0F);
        Shape6 = new ModelRenderer(this, 0, 0);
        Shape6.addBox(0F, 0F, 0F, 3, 1, 1);
        Shape6.setRotationPoint(-8F, 10F, 4F);
        Shape6.setTextureSize(128, 128);
        Shape6.mirror = true;
        setRotation(Shape6, 0F, 0F, 0F);
        Shape7 = new ModelRenderer(this, 0, 0);
        Shape7.addBox(-8F, 0F, 0F, 3, 1, 1);
        Shape7.setRotationPoint(0F, 10F, -5F);
        Shape7.setTextureSize(128, 128);
        Shape7.mirror = true;
        setRotation(Shape7, 0F, 0F, 0F);
        Shape8 = new ModelRenderer(this, 0, 0);
        Shape8.addBox(0F, 0F, 0F, 1, 1, 3);
        Shape8.setRotationPoint(-5F, 10F, 5F);
        Shape8.setTextureSize(128, 128);
        Shape8.mirror = true;
        setRotation(Shape8, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Corner1.render(f5);
        Corner2.render(f5);
        Corner3.render(f5);
        Corner4.render(f5);
        Bookshelve.render(f5);
        Base2.render(f5);
        TCorner1.render(f5);
        TCorner2.render(f5);
        TCorner3.render(f5);
        TCorner4.render(f5);
        Top.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
    }

    public void renderModel(float f5) {
        Base.render(f5);
        Corner1.render(f5);
        Corner2.render(f5);
        Corner3.render(f5);
        Corner4.render(f5);
        Bookshelve.render(f5);
        Base2.render(f5);
        TCorner1.render(f5);
        TCorner2.render(f5);
        TCorner3.render(f5);
        TCorner4.render(f5);
        Top.render(f5);
        Shape1.render(f5);
        Shape2.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
        Shape6.render(f5);
        Shape7.render(f5);
        Shape8.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
